[package]
name = "tauri-plugin-secure-storage"
version = "2.0.0"
edition = "2024"
rust-version = "1.85"
authors = { workspace = true }
license = { workspace = true }
repository = { workspace = true }
links = "tauri-plugin-secure-storage"
description = "Store data in the platforms' keychains."

[package.metadata.docs.rs]
rustc-args = ["--cfg", "docsrs"]
rustdoc-args = ["--cfg", "docsrs"]

# Platforms supported by the plugin
# Support levels are "full", "partial", "none", "unknown"
# Details of the support level are left to plugin maintainer
[package.metadata.platforms]
windows = { level = "full", notes = "Windows' credentials storage only protects from other accounts on that system. The main user and their apps can access your app's data." }
linux = { level = "partial", notes = "For this PoC on Linux the storage is in-memory only and will be reset on reboot." }
macos = { level = "full", notes = "May prompt for passwords twice." }
android = { level = "full", notes = "The implementation is very new and therefore not battle-tested nor audited." }
ios = { level = "full", notes = "" }

[build-dependencies]
tauri-plugin = { workspace = true, features = ["build"] }

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }
tauri = { workspace = true }
log = { workspace = true }
thiserror = { workspace = true }
# When updating to v4 we likely won't use linux-native aka keyutils but we need to look into which backend to use.
# Also, `linux-native` is non persistent.
keyring = { version = "3.6", features = [
  "apple-native",
  "windows-native",
  "linux-native",
] }

[target."cfg(target_os = \"android\")".dependencies]
android-keyring = "0.2.0"
